export enum Category {
  GARDENING = 'GARDENING',
  CONSTRUCTION = 'CONSTRUCTION',
  ELECTRIC = 'ELECTRIC',
  PLUMBING = 'PLUMBING',
  AUTOMOTIVE = 'AUTOMOTIVE',
  PAINTING = 'PAINTING',
  CLEANING = 'CLEANING',
  WOODWORKING = 'WOODWORKING',
  METALWORKING = 'METALWORKING',
  OUTDOOR = 'OUTDOOR',
  OTHER = 'OTHER'
}
